base_url = "https://alectronix.net"
title = "Alectronix"
description = "A Personal Electronics Hobby Blog"

compile_sass = true
build_search_index = false
#theme = "d3c3nt"

default_language = "en"

minify_html = true

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = true

[extra]
# Put all your custom variables here
  d3_nav = [
    { name = "Home", path = "/" },
    { name = "Projects", path = "/posts/" },
    { name = "Config", path = "/config/" },
  ]
  d3_icon = "/icon.png"
  d3_twitter = "N/A"
  d3_author = "Xalllle"